name: Infra Apply + Lambda Trigger

on:
  schedule:
    - cron: '0 0 * * *'   # 09:00 KST (NAT ON)
    - cron: '0 13 * * *'  # 22:00 KST (NAT OFF)
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform/v2/envs/infra

    steps:
      - name: Checkout with submodules
        uses: actions/checkout@v3
        with:
          submodules: true
          token: ${{ secrets.REPO_TOKEN}}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply (NAT ON/OFF with submodule tfvars)
        run: |
          HOUR=$(date -u +"%H")
          NAT_ENABLED="false"
          if [ "$HOUR" -eq "0" ]; then
            NAT_ENABLED="true"
          fi

          terraform apply \
            -auto-approve \
            -target=module.nat \
            -var-file=../../../../terraform-properties/v2/infra_terraform.tfvars \
            -var="enable_natgw=${NAT_ENABLED}"
            -var="assignee_tag=github"

  lambda_trigger:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Invoke Lambda (mode=startup/shutdown)
        run: |
          HOUR=$(date -u +"%H")
          MODE="shutdown"
          if [ "$HOUR" -eq "0" ]; then
            MODE="startup"
          fi

          curl -X POST "${{ secrets.API_GATEWAY }}/lambda-trigger" \
               -H "Content-Type: application/json" \
               -d "{\"mode\": \"${MODE}\"}"
